# Laboratorio de regresión - 3

## Significancia de factores

|                |   |
:----------------|---|
| **Nombre**     |Damarys Valenzuela Santos|
| **Fecha**      |31/08/2025|
| **Expediente** |744494|

Descarga el archivo de publicidad y carga los datos (Advertising.csv).

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import r2_score

In [ ]:
df = pd.read_csv("Advertising.csv")
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

**¿Hay alguna relación entre el presupuesto para publicidad y las ventas?**

Nuestra primera meta debe ser determinar si hay evidencia en los datos de que haya una asociación entre estas variables.

- ¿Por qué? ¿Qué resultaría si nos diéramos cuenta de la falta de relación entre el presupuesto de publicidad y las ventas?

Si no existe una relación entre el presupuesto de publicidad y las ventas, no tendría sentido seguir destinando dinero a la publicidad, ya que no estaría generando resultados.

**¿Qué tan fuerte es esta relación?**
Asumiendo que existe esta relación, ¿nos sirve conocer el impacto que tiene invertir en publicidad en las ventas?

Esto nos permite evaluar si la inversión en publicidad realmente vale la pena, ya que podría tener un impacto, pero muy limitado.

**¿Cuáles medios están asociados con las ventas? ¿Qué tan grande es la asociación entre un medio específico y las ventas?**

Hay 3 medios distintos en los datos. ¿Sirve invertir en los 3? ¿Conviene más invertir sólo en uno?

**¿Qué tan seguros estamos de que podríamos predecir ventas futuras?**

**¿La relación es lineal?**

**¿Hay sinergia entre estos medios?**

Puede ser que gastar \\$50,000 en publicidad y otros \\$50,000 en radio es mejor opción que gastar \\$100,000 en televisión. A esto le llamamos efecto de interacción.

Podemos usar regresión lineal para responder todas estas preguntas.

Realiza una regresión lineal:

$$ \text{ventas} \approx \beta_0 + (\beta_1)(\text{TV})$$

In [ ]:
x = df[["TV"]].values
y = df[["sales"]].values
X = x.reshape(-1, 1)

In [ ]:
modelo = LinearRegression()
modelo.fit(X, y)
y_pred = modelo.predict(X)
print(modelo.intercept_,modelo.coef_)

[7.03259355] [[0.04753664]]


In [ ]:
beta0_hat = modelo.intercept_
beta1_hat = modelo.coef_

### Verificando la precisión de nuestros coeficientes estimados

Recuerda que en el mundo real hay ruidos y errores de medición. Siempre se asume que la verdadera relación entre $X$ y $Y$ es $$Y = \beta_0 + \beta_1 X + \epsilon$$

Se asume que el término de error es independiente de $X$ (el error siempre es el mismo sin importar el valor de $X$). Este modelo describe a la *línea de regresión de la población*, que es la mejor aproximación de la verdadera relación entre $X$ y $Y$. Cuando usamos mínimos cuadrados encontramos la *línea de mínimos cuadrados*.

¿Cuál es la diferencia entre población y muestra?

Población es todo el grupo que nos interesa estudiar, y muestra es un subconjunto de la población.

¿Cuál crees que sea la diferencia entre hacer una regresión con todos los datos de la población y una muestra de ella?

Si lo hacemos con toda la población, obtenemos los verdaderos coeficientes, y si solo usamos una muestra, los coeficientes que obtenemos son las aproximaciones.

La línea de regresión de la población no se puede observar. El concepto de comparar estas líneas es una extensión natural del acercamiento estadístico estándar de usar información de una muestra para estimar características de una población grande.

Imagina que quieres encontrar la altura promedio de un mexicano $\mu$. Medir a todos y cada uno de los mexicanos en situaciones similares, con la misma regla, mismo operador, y otras incontables formas de minimizar la variación de la medida es una tarea imposible. Lo que podemos asumir es que $\hat{\mu} = \bar{y}$. La media poblacional y la media muestral son diferentes, pero la media muestral es usualmente un buen estimado.

De la misma manera, como no contamos con el 100% de la información para hacer una regresión, los coeficientes $\beta_0$ y $\beta_1$ son desconocidos. Podemos estimarlos usando mínimos cuadrados, encontrando $\hat{\beta_0}$ y $\hat{\beta_1}$. Puede que las muestras que tengamos en ese momento estén un poco por encima de la media, pero otras muestras en otro momento puede que estén debajo de la media. En general, esperamos que el promedio de las aproximaciones $\hat{\mu}$ aproxime a $\mu$.

Esto lleva a la pregunta: ¿qué tan cercanos son nuestros coeficientes estimados a los verdaderos coeficientes? Utilizamos el concepto de error estándar para evaluar esto.

$$ \text{Var}(\hat{\mu})=\text{SE}(\hat{\mu})^2 = \frac{\sigma^2}{n} $$

Donde $\sigma$ es la desviación estándar de cada una de las observaciones $y_i$ de $Y$. El error estándar nos dice la cantidad promedio que el estimado difiere del valor verdadero. Podemos ver en la fórmula que entre más observaciones tengamos el error se hace más pequeño. Las fórmulas para errores estándar de $\hat{\beta_0}$ y $\hat{\beta_1}$ son:

$$ \text{SE}(\hat{\beta_0})^2 = \sigma^2 [\frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^n (x_i - \bar{x})^2}]$$

$$ \text{SE}(\hat{\beta_1})^2 = \frac{\sigma^2}{\sum_{i=1}^n (x_i - \bar{x})^2}$$

$$ \sigma^2 = \text{Var}(\epsilon) = \text{RSE}^2 = \frac{\text{RSS}}{n-p}$$

Para que estas fórmulas sean validas asumimos que los errores $\epsilon_i$ tienen varianza común $\sigma^2$ y que no están correlacionados.

Calcula los errores estándar de los coeficientes

In [ ]:
resid = y - y_pred
n = len(y)
p = 2  # intercepto y pendiente
RSS = np.sum(resid**2)
sigma2 = RSS / (n - p)
print(RSS,sigma2)


2102.5305831313512 10.618841328946218


In [ ]:
x_bar = x.mean()
Sxx = np.sum((x - x_bar)**2)


In [ ]:
SE_beta1 = np.sqrt(sigma2 / Sxx)
SE_beta0 = np.sqrt(sigma2 * (1/n + (x_bar**2)/Sxx))
print(SE_beta0,SE_beta1)

0.4578429402734785 0.0026906071877968707


Estos errores se pueden usar para calcular intervalos de confianza. Un intervalo de confianza del $95\%$ se define como un rango de valores en el cuál se encuentra el desconocido valor verdadero con un $95\%$ de probabilidad.

Otra forma de verlo es que si tomamos muestras repetidas y construimos un intervalo de confianza para cada una, el $95\%$ de los intervalos creados van a contener el valor verdadero. Para la regresión el intervalo de confianza del $95\%$ toma la forma:

$$ \hat{\beta_j} \pm 2\text{SE}(\hat{\beta_j})$$

Calcula los intervalos de confianza para los coeficientes estimados:

In [ ]:
beta0_hat+2*SE_beta0

array([7.94827943])

In [ ]:
beta0_hat-2*SE_beta0

array([6.11690767])

In [ ]:
beta1_hat+2*SE_beta1

array([[0.05291785]])

In [ ]:
beta1_hat-2*SE_beta1

array([[0.04215543]])

Los errores estándar también se usan para realizar pruebas de hipótesis. La prueba de hipótesis más común es probar la hipótesis nula de:

$$ H_0: \text{No hay relación entre } X \text{ y } Y \ \ \ \ (\beta_1=0)$$

contra la hipótesis alternativa:
$$ H_0: \text{Hay alguna relación entre } X \text{ y } Y \ \ \ (\beta_1 \neq 0)$$

Explica con tus palabras el significado de la hipótesis nula y la hipótesis alternativa.

Podemos decirlo así de manera más clara:

La hipótesis nula generalmente representa **la situación “sin efecto” o “sin cambio”**, que se asume como cierta hasta que los datos demuestren lo contrario. Por ejemplo, β1 = 0 significa que X no tiene impacto sobre Y. Si los datos muestran evidencia suficiente, podemos rechazar la hipótesis nula y aceptar la alternativa; si no, la hipótesis nula se mantiene.


Para probal la hipótesis nula debemos determinar si nuestro estimado $\hat{\beta_1}$ de $\beta_1$ está lo suficientemente alejado de cero para que podamos decir con confianza que este valor no es cero.

¿Qué tan lejos? Depende de qué tanta confianza tengamos en el estimado encontrado. Si nuestro error estándar es pequeño y nuestro estimado está alejado de cero podríamos decir que hay muy poca probabilidad de que el valor verdadero sea 0. En cambio, si nuestro error estándar es grande y nuestro estimado está muy cerca de cero, entonces podrías ser que el valor verdadero sea cero y que no haya relación entre las variables.

Se calcula un *estadístico t* dado por
$$ t = \frac{\hat{\beta_j} - \mu}{\text{SE}(\hat{\beta_j})} $$

donde $\mu$ es el valor contra el que queremos probar.

Calcula el estadístico t para tus coeficientes estimados, usando como referencia la prueba de hipótesis.

In [ ]:
from scipy import stats
p=2
t_beta1= beta1_hat/SE_beta1
t_beta0= beta0_hat/SE_beta0
df= n-p

print("t=",t_beta0)
print("t=",t_beta1)

t= [15.36027517]
t= [[17.6676256]]


Hi: B =/ 0

In [ ]:
from scipy import stats

# Grados de libertad
df = n - p

# Estadísticos t
t_beta0 = beta0_hat / SE_beta0
t_beta1 = beta1_hat / SE_beta1

# p-values bilaterales
p_beta0 = 2 * (1 - stats.t.cdf(abs(t_beta0), df=df))
p_beta1 = 2 * (1 - stats.t.cdf(abs(t_beta1), df=df))


print("beta0: t =", t_beta0, " p-value =", p_beta0, " -->", "Rechazo H0" if p_beta0 < 0.05 else "No rechazo H0")
print("beta1: t =", t_beta1, " p-value =", p_beta1, " -->", "Rechazo H0" if p_beta1 < 0.05 else "No rechazo H0")


beta0: t = [15.36027517]  p-value = [0.]  --> Rechazo H0
beta1: t = [[17.6676256]]  p-value = [[0.]]  --> Rechazo H0


La distribución t tiene forma de campana y se parece bastante a la distribución normal cuando $n > 30$. Ya sólo es cuestión de calcular la probabilidad de observar cualquier número tal que su valor absoluto sea igual o mayor que el valor absoluto del estadístico t calculado. En otras palabras:
$$ P(|x| \geq |t|) $$

A esta probabilidad la llamamos *p-value*. Un *p-value* pequeño indica que es poco probable que exista por puro azar una relación significativa entre predictor y respuesta, en caso de que no haya una asociación real entre predictor y respuesta. En otras palabras, el *p-value* te dice la probabilidad de que parezca que hay relación cuando no la hay.

Si el *p-value* es pequeño, inferimos que sí hay una asociación entre el predictor y la respuesta, y **rechazamos la hipótesis nula**.
  

¿Qué tan pequeño? Depende de la aplicación. Un valor muy común es del $5\%$.

Utiliza el siguiente código para calcular el *p-value* para tus coeficientes

`from scipy import stats`

`p_bj = 2*(1 - stats.t.cdf(np.abs(t_bj), n-p))`

In [ ]:
from scipy import stats
p_bj0 = 2*(1 - stats.t.cdf(np.abs(t_beta0), n-p))
p_bj0

array([0.])

In [ ]:
p_bj1 = 2*(1 - stats.t.cdf(np.abs(t_beta1), n-p))
p_bj1

array([[0.]])

¿Se rechaza la hipótesis nula? ¿Qué significa?

Rechazar H0 significa que hay evidencia para decir que X que es TV sí afecta a Y.

Realiza otras dos regresiones. Ya tienes hecha la regresión de ventas dado el gasto en publicidad de TV. Realiza la regresión para gastos en radio y gastos en periódico. Organiza las respuestas para que debajo de esta celda se tenga:
- Título de regresión
- Coeficientes estimados
- Errores estándar de los coeficientes
- Intervalos de confianza
- Estadísticos t
- p-values
- Observaciones

# Ventas y radio

In [ ]:
df = pd.read_csv("Advertising.csv")
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

# Coeficientes estimados

In [ ]:
x = df[["radio"]].values
y = df[["sales"]].values
X = x.reshape(-1,1)
y = y.reshape(-1,1)
modelo = LinearRegression()
modelo.fit(X, y)
y_pred = modelo.predict(X)
print(modelo.intercept_,modelo.coef_)

[9.3116381] [[0.20249578]]


#Errores estándar de los coeficientes

In [ ]:
resid = y - y_pred
n = len(y)
p = 2  # intercepto y pendiente
RSS = np.sum(resid**2)
sigma2 = RSS / (n - p)
x_bar = x.mean()
Sxx = np.sum((x - x_bar)**2)
SE_beta1 = np.sqrt(sigma2 / Sxx)
SE_beta0 = np.sqrt(sigma2 * (1/n + (x_bar**2)/Sxx))
print(SE_beta0,SE_beta1)

0.5629004962718711 0.020411306360090635


# Intervalos de confianza

In [ ]:
# Intervalos para beta0
interval_beta0_plus = modelo.intercept_ + 2*SE_beta0
interval_beta0_minus = modelo.intercept_ - 2*SE_beta0

# Intervalos para beta1
interval_beta1_plus = modelo.coef_ + 2*SE_beta1
interval_beta1_minus = modelo.coef_ - 2*SE_beta1

print("Intervalo aproximado para beta0:")
print("beta0_hat - 2*SE_beta0:", interval_beta0_minus)
print("beta0_hat + 2*SE_beta0:", interval_beta0_plus)

print("\nIntervalo aproximado para beta1:")
print("beta1_hat - 2*SE_beta1:", interval_beta1_minus)
print("beta1_hat + 2*SE_beta1:", interval_beta1_plus)


Intervalo aproximado para beta0:
beta0_hat - 2*SE_beta0: [8.1858371]
beta0_hat + 2*SE_beta0: [10.43743909]

Intervalo aproximado para beta1:
beta1_hat - 2*SE_beta1: [[0.16167317]]
beta1_hat + 2*SE_beta1: [[0.2433184]]


# Estadísticos t

In [ ]:
from scipy import stats
p=2
t_beta1= modelo.coef_/SE_beta1
t_beta0= modelo.intercept_/SE_beta0
df= n-p

print("t=",t_beta0)
print("t=",t_beta1)

t= [16.54224531]
t= [[9.92076547]]


# p-values

In [ ]:
p_bj0 = 2*(1 - stats.t.cdf(np.abs(t_beta0), n-p))
p_bj1 = 2*(1 - stats.t.cdf(np.abs(t_beta1), n-p))
print(p_bj0,p_bj1)

[0.] [[0.]]


# Observaciones
Se rechaza H0 hay evidencia estadística suficiente para afirmar que X sí tiene relación con Y.

# Ventas y periodico
# Coeficientes estimados

In [ ]:
df = pd.read_csv("Advertising.csv")
x = df[["newspaper"]].values
y = df[["sales"]].values
X = x.reshape(-1,1)
y = y.reshape(-1,1)
modelo = LinearRegression()
modelo.fit(X, y)
y_pred = modelo.predict(X)
print(modelo.intercept_,modelo.coef_)

[12.35140707] [[0.0546931]]


# Errores estándar de los coeficientes

In [ ]:
resid = y - y_pred
n = len(y)
p = 2  # intercepto y pendiente
RSS = np.sum(resid**2)
sigma2 = RSS / (n - p)
x_bar = x.mean()
Sxx = np.sum((x - x_bar)**2)
SE_beta1 = np.sqrt(sigma2 / Sxx)
SE_beta0 = np.sqrt(sigma2 * (1/n + (x_bar**2)/Sxx))
print(SE_beta0,SE_beta1)

0.6214201876094345 0.016575721876358165


# Intervalos de confianza

In [ ]:
# Intervalos para beta0
interval_beta0_plus = modelo.intercept_ + 2*SE_beta0
interval_beta0_minus = modelo.intercept_ - 2*SE_beta0

# Intervalos para beta1
interval_beta1_plus = modelo.coef_ + 2*SE_beta1
interval_beta1_minus = modelo.coef_ - 2*SE_beta1

print("Intervalo aproximado para beta0:")
print("beta0_hat - 2*SE_beta0:", interval_beta0_minus)
print("beta0_hat + 2*SE_beta0:", interval_beta0_plus)

print("\nIntervalo aproximado para beta1:")
print("beta1_hat - 2*SE_beta1:", interval_beta1_minus)
print("beta1_hat + 2*SE_beta1:", interval_beta1_plus)


Intervalo aproximado para beta0:
beta0_hat - 2*SE_beta0: [11.10856669]
beta0_hat + 2*SE_beta0: [13.59424744]

Intervalo aproximado para beta1:
beta1_hat - 2*SE_beta1: [[0.02154165]]
beta1_hat + 2*SE_beta1: [[0.08784454]]


# Estadísticos t

In [ ]:
p=2
t_beta1= modelo.coef_/SE_beta1
t_beta0= modelo.intercept_/SE_beta0
df= n-p

print("t=",t_beta0)
print("t=",t_beta1)

t= [19.87609562]
t= [[3.29959074]]


# p-values

In [ ]:
p_bj0 = 2*(1 - stats.t.cdf(np.abs(t_beta0), n-p))
p_bj1 = 2*(1 - stats.t.cdf(np.abs(t_beta1), n-p))
print(p_bj0,p_bj1)

[0.] [[0.0011482]]


# Observaciones
También se rechaza H0 por lo cual el periodico si tiene impacto en las ventas.

## Regresión lineal múltiple

En lugar de hacer una regresión para cada factor independiente, quizás se puede extender el modelo para que tenga varios factores dentro:

$$ Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + ... + \beta_p X_p + \epsilon $$

Para nuestro ejemplo de publicidad:

$$ \text{sales} = \beta_0 + \beta_1 (\text{TV}) + \beta_2 (\text{radio}) + \beta_3 (\text{newspaper}) + \epsilon $$

Utiliza la librería `statsmodels` para realizar la regresión. Por defecto la librería statsmodels no toma en cuenta el intercepto ($\beta_0$), por lo que se tendrá que agregar una columna de unos de tamaño *n* a la matriz X.

`import statsmodels.api as sm`

`ols = sm.OLS(Y, X)`

`results = ols.fit()`

`results.summary()`

In [ ]:
import statsmodels.api as sm
df = pd.read_csv("Advertising.csv")
X = df[["TV", "radio", "newspaper"]].values
X = sm.add_constant(X)
Y = df["sales"].values
ols = sm.OLS(Y, X)
results = ols.fit()
print(results.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Mon, 01 Sep 2025   Prob (F-statistic):           1.58e-96
Time:                        03:29:29   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.0

¿Qué diferencias puedes observar entre los *p-values* de una regresión múltiple y los encontrados en las regresiones simples? ¿Por qué crees que existen estas diferencias?

En esto no se rechaza la H0 en newspaper no hay evidencia de que afecte las ventas. No se porque cambie en este modelo multiple.

## Referencia

James, G., Witten, D., Hastie, T., Tibshirani, R.,, Taylor, J. (2023). An Introduction to Statistical Learning with Applications in Python. Cham: Springer. ISBN: 978-3-031-38746-3

## Addendum

Para calcular los *p-values* de los parámetros sin `statsmodels`:
1. Calcular RSS
2. Calcular RSE
3. `var_beta = np.linalg.inv(X.T @ X) * rse**2` (X con columna de intercepto)
4. `std_beta = np.sqrt(var_beta.diagonal())` El orden de los valores corresponde al orden de los factores en las columnas de la matriz $X$.
5. Calcular *estadístico t*
6. Calcular *p-value*

In [ ]:
from sklearn.linear_model import LinearRegression
from scipy import stats
X = df[["TV"]]          # matriz (n,1)
y = df["sales"].values  # vector (n,)

n, k = X.shape

# 2) Agregar intercepto (columna de 1s)
X_aug = np.column_stack([np.ones(n), X])

# 3) Ajustar modelo
model = LinearRegression(fit_intercept=False).fit(X_aug, y)
beta_hat = model.coef_.reshape(-1, 1)      # (2,1): [intercepto, beta1]

# 4) Predicciones y residuos
y_hat = model.predict(X_aug)
resid = y.reshape(-1,1) - y_hat.reshape(-1,1)

# 5) RSS y sigma²
RSS = float(resid.T @ resid)
p = X_aug.shape[1]  # número de parámetros (2: intercepto + pendiente)
sigma2 = RSS / (n - p)

# 6) Var(beta) y errores estándar
XtX_inv = np.linalg.inv(X_aug.T @ X_aug)
var_beta = sigma2 * XtX_inv
std_beta = np.sqrt(np.diag(var_beta))

# 7) t-stats y p-values
t_stats = (beta_hat.flatten()) / std_beta
dfree = n - p
p_vals = 2 * (1 - stats.t.cdf(np.abs(t_stats), df=dfree))

# 8) Resultados
for j, (bj, se, tj, pv) in enumerate(zip(beta_hat.flatten(), std_beta, t_stats, p_vals)):
    name = "beta0 (intercepto)" if j == 0 else "beta1 (TV)"
    decision = "Rechazo H0" if pv < 0.05 else "No rechazo H0"
    print(f"{name}: beta = {bj:.4f}, SE = {se:.4f}, t = {tj:.4f}, p-value = {pv:.4g} --> {decision}")

beta0 (intercepto): beta = 7.0326, SE = 0.4578, t = 15.3603, p-value = 0 --> Rechazo H0
beta1 (TV): beta = 0.0475, SE = 0.0027, t = 17.6676, p-value = 0 --> Rechazo H0


/tmp/ipython-input-3702009144.py:20: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  RSS = float(resid.T @ resid)
